management.endpoints.web.exposure.include: "*"

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:9000/eureka
   instance:
      preferIpAddress: true
      hostname: 13.113.245.83
      
