management.endpoints.web.exposure.include: "*"

spring:
  zipkin:
        baseUrl: http://localhost:9411  
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
         #defaultZone: http://localhost:8761/eureka
   instance:
      preferIpAddress: true
      hostname: localhost
 
      
